#!/usr/bin/env bash
# Install nginx
sudo apt update
sudo apt install nginx -y

service nginx start
# Configure nginx to listen on port 80


# Configure nginx to return "Hello World!" at root /
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart nginx
if [ -x "$(command -v systemctl)" ]; then
    sudo systemctl restart nginx
else
    sudo service nginx restart
fi
