#!/usr/bin/env bash
# Install nginx
sudo apt update
sudo apt install nginx -y

service nginx start
# Configure nginx to listen on port 80
ufw allow 'Nginx HTTP'

# Configure nginx to return "Hello World!" at root /
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart nginx
sudo service nginx restart
