#!/usr/bin/env bash
sudo apt update
sudo apt install nginx
sudo systemctl start nginx
sudo sed -i '/^http {/a \    server {\n        listen 80;\n        server_name _;\n        location / {\n            root /var/www/html;\n            index index.html;\n        }\n    }' /etc/nginx/nginx.conf
sudo ufw allow 80/tcp
