#!/usr/bin/env bash
# Bash script to install and configure Nginx on Ubuntu to listen on port 80 
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
rm /run/nginx.pid
