#!/usr/bin/env bash
# Configures an Ubuntu Server to have localhost resolve to 127.0.0.2 and facebook.com resolve to 8.8.8.8

# Create a backup of the existing hosts file
cp /etc/hosts /etc/hosts.bak

# Update the hosts file
sed -i '/127.0.0.1/c\127.0.0.2 localhost' /etc/hosts
echo -e '8.8.8.8\tfacebook.com' >> /etc/hosts

# Flush DNS cache
/etc/init.d/dns-clean restart

# Check if the config is correct
host localhost | grep '127.0.0.2'
host facebook.com | grep '8.8.8.8'
