#!/bin/bash
git add . && git commit -m 'commit message' && git push#!/bin/bash
git add . && git commit -m 'commit message' && git push#!/bin/bash
git add . && git commit -m 'commit message' && git push
